### PR TITLE
[WIP] Transitory Changes as adapted from BitCoin Core

### PR DESCRIPTION
**Pull request by ghost**
#### What is the purpose of this pull request (PR)?

To adopt certain changes as per BitCoin Convention Standards as pertaining to C++11 Standards

#### Any background context to help the reviewer?

The (hopefully) final PR will be derived from https://github.com/bitcoin/bitcoin/pull/8342, https://github.com/bitcoin/bitcoin/pull/4025, https://github.com/bitcoin/bitcoin/pull/9289, https://github.com/bitcoin/bitcoin/pull/9387, https://github.com/bitcoin/bitcoin/pull/9476

#### Was this PR tested and how?

It's a Work In Progress but is currently worked on an Ubuntu 16.04 LTS on VMWare WorkStation 11 on Windows 10 Setup

#### More Questions:

- Does the knowledge base need an update? Possibly

- Does this PR add or change dependencies? No

- Does this PR change or fork the blockchain? No

### CODE REVIEW

**Comment by SCDeveloper** [comment]
Please review the Travis-CI tests and repair.

**Comment by ghost** [comment]
Okay, done Spence

**Comment by empinel** [comment]
Resolved

**Comment by ghost** [comment]
PR is approved for new testing and merging (based on Ubuntu Testing on 00b592b)

**Comment by empinel** [comment]
Bump

**Comment by SCDeveloper** [comment]
Please PR to v1.1.0.0 branch.

**Comment by ghost** [comment]
Done

**Pull request merged**
