### PR TITLE
Removal of unneeded files

### PR DESCRIPTION
**Pull request by quantumgravity444**
#### What is the purpose of this pull request (PR)?

Removes unneeded files that were added to the repo by mistake or are artifacts from Bitcoin that should have been removed.

### CODE REVIEW

**Comment by quantumgravity444** [comment]
Travis failed due to issues with ZMQ. This PR does not affect anything with the build whatsoever.

**Comment by AmirAbrams** [comment]
I restarted Travis.  I don't see why it would fail either.  utACK.

**Comment by AmirAbrams** [comment]
It failed because share/setup.nsi.in was removed.

**Comment by quantumgravity444** [comment]
It should pass Travis now..

**Review by AmirAbrams — APPROVED** [review]
utACK.

**Pull request merged**
