### PR TITLE
[WIP][Build] Update depends boost and qt versions

### PR DESCRIPTION
**Pull request by AmirAbrams**
### What is the purpose of this pull request (PR)?

Updates depends build environment to use boost v 1.59 and Qt 5.6.

### CODE REVIEW

**Comment by AmirAbrams** [comment]
Do not merge yet.  Still a work in progress.

**Comment by GregoryBetz** [comment]
Tested ACK

**Comment by AmirAbrams** [comment]
It depends doesn't work for Windows builds yet: [doc/build-windows.md](https://github.com/SilkNetwork/Silk-Core/blob/master/doc/build-windows.md).  The silk-qt.exe builds but doesn't work.  silkd.exe, silk-cli.exe and silk-tx all work.  The problem stems form this line in src/qt/silk.cpp:
```
#if defined(QT_STATICPLUGIN) && QT_VERSION < 0x050000 
Q_IMPORT_PLUGIN(qcncodecs) 
Q_IMPORT_PLUGIN(qjpcodecs) 
Q_IMPORT_PLUGIN(qtwcodecs) 
Q_IMPORT_PLUGIN(qkrcodecs) 
Q_IMPORT_PLUGIN(qtaccessiblewidgets) 
#if defined(QT_QPA_PLATFORM_XCB) 
Q_IMPORT_PLUGIN(QXcbIntegrationPlugin); 
#elif defined(QT_QPA_PLATFORM_WINDOWS) 
Q_IMPORT_PLUGIN(QWindowsIntegrationPlugin); 
#elif defined(QT_QPA_PLATFORM_COCOA) 
Q_IMPORT_PLUGIN(QCocoaIntegrationPlugin); 
#endif 
#endif 
```
If I revert to the original src/qt/silk.cpp code, I get this build error for Windows 32/64 builds:
>   GEN      qt/locale/silk_zh_CN.qm
>   GEN      qt/locale/silk_zh_HK.qm
>   GEN      qt/locale/silk_zh_TW.qm
>   GEN      qt/qrc_silk_locale.cpp
>   CXX      qt/qt_libsilkqt_a-qrc_silk_locale.o
>   AR       qt/libsilkqt.a
> /usr/bin/i686-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
>   OBJCXXLD qt/silk-qt.exe
> qt/qt_silk_qt-silk.o:silk.cpp:(.text.startup+0xf9): undefined reference to `qt_static_plugin_AccessibleFactory()'
> collect2: error: ld returned 1 exit status
> Makefile:2353: recipe for target 'qt/silk-qt.exe' failed
> make[2]: *** [qt/silk-qt.exe] Error 1

The current depends can build Windows binaries so I can't merge until this can do the same.

**Comment by GregoryBetz** [comment]
Ah I see. I just built and ran the wallet on Ubuntu. I never tried building a windows binary with depends.

**Pull request closed without merging**
